variable "name" {}
variable "vpc" {}
variable "bastion_sg" {}
variable "nr_key" {}
variable "nr_acct_id" {}
variable "keypair" {}
variable "subnet1_id" {}
variable "subnet2_id" {}
variable "acm_certificate_arn" {}
variable "domain" {}
variable "subnet" {}
